version: 2
jobs:
  build-go1.10.1:
    docker:
        - image: golang:1.10.1
    working_directory: /go/src/github.com/lessor/lessor
    steps: &steps
      - checkout
      - run: make deps
      - run: make test
      - run: make
workflows:
  version: 2
  build:
    jobs:
      - build-go1.10.1
