version: 2
jobs:
  build-go1.10.1:
    docker:
        - image: golang:1.10.1
    working_directory: /go/src/github.com/lessor/lessor
    steps: &steps
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - run: go test -race -cover -v ./...
      - run: go build ./cmd/lessor
workflows:
  version: 2
  build:
    jobs:
      - build-go1.10.1
